target:
  _target_: calo_cluster.models.base_lightning.BaseLightningModule
pres: 1.0
vres: 1.0
cr: 1.0
cs: [32, 32, 64, 128, 256, 256, 128, 96, 96]
seed: ${seed}
sparse: True
tanh_scale: null
backbone:
  _target_: calo_cluster.models.dsnet.DSNetBackbone