_target_: calo_cluster.evaluation.callbacks.metric_callback.MetricCallback

metric:
  _target_: calo_cluster.evaluation.metrics.calo.Response
  name: ${name}
  bins: [0, 0.5, 1, 2, 3, 6, 10, 20, 50, 100]
  num_classes: 2
  semantic: True
  ignore_index: null
  ignore_semantic_labels: [0]
  threshold: 0.5
  min_hits: 0
  use_target: False
  clusterer: ${clusterer}
  use_nn: True
  target_instance_label_name: PFcluster0Id
