_target_: calo_cluster.evaluation.studies.calo_study.ResponseCallback
clusterer:
  _target_: calo_cluster.clustering.meanshift.MeanShift
  use_gpu: False
  bandwidth: 0.1
  use_semantic: True
  ignore_semantic_labels: [0]
  n_jobs: 1
metric:
  _target_: calo_cluster.evaluation.metrics.calo.Response
  bins: [0, 0.5, 1, 2, 3, 6, 10]
  num_classes: 2
  semantic: True
  ignore_index: null
  ignore_semantic_labels: [0]
  threshold: 0.5
path: ???
use_target: True
target_instance_label_name: PFcluster0Id