_target_: calo_cluster.evaluation.callbacks.metric_callback.MetricCallback
metric:
  _target_: calo_cluster.evaluation.metrics.instance.PanopticQuality
  experiment: ${experiment}
  name: ${name}
  num_classes: 2
  ignore_index: null
  ignore_semantic_labels: [0]
  clusterer: ${clusterer}
  use_target: False
  target_instance_label_name: PFcluster0Id

