_target_: calo_cluster.evaluation.studies.clustering_study.PQCallback
clusterer: ${clusterer}
pq:
  _target_: calo_cluster.evaluation.metrics.instance.PanopticQuality
  num_classes: 2
  ignore_index: null
  ignore_semantic_labels: [0]

use_target: False
target_instance_label_name: PFcluster0Id