seed: ${seed}
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}
sparse: ${model.sparse}

num_workers: 8

# fraction of data to use (needs to be supported by dataset):
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1

# optional scale factors for features/coords
transform_features: False
features_loc: null
features_scale: null

transform_coords: False
coords_loc: null
coords_scale: null

# optional weights for each class
class_weights: null

valid_semantic_labels_for_clustering: ???
invalid_semantic_label_for_classification: -100

# the dimension that contains batch information (only relevant if sparse=False)
batch_dim: 0

# required fields (set to null if not relevant to dataset):
num_classes: ???
num_features: ???
voxel_size: ???
data_dir: ???
