defaults:
  - base_dataset
_target_: calo_cluster.datasets.hcal_tt_pu200_pf.HCalTTPU200PFDataModule

# required fields:
num_classes: 2
num_features: 6
voxel_size: 0.1

# dataset-specific fields (should not change):
noise_id: -99
valid_semantic_labels_for_clustering: [1]
semantic_label: pf_hit
instance_label: PFcluster0Id
weight: energy

# data location (modify as needed):
data_dir: ${data_dir}/hcal/tt_mu_200/
raw_data_dir: ${data_dir}/hcal/tt_mu_200/raw

# config fields:
feats: ['eta', 'phi', 'x', 'y', 'z', 'energy']
coords: ['eta', 'phi',]
min_hits_per_cluster: null
min_cluster_energy: null
min_eta: null
max_eta: null
aux: null