defaults:
  - base_dataset
_target_: calo_cluster.datasets.kitti.KITTIDataModule

# required fields:
num_classes: 19
num_features: 4
voxel_size: 0.05

# dataset-specific fields (should not change):
valid_semantic_labels_for_clustering: [0, 1, 2, 3, 4, 5, 6, 7]
invalid_semantic_label_for_classification: 255

# data location (modify as needed):
data_dir: ${data_dir}/kitti/dataset/sequences

# config fields:
class_weights: [2.293, 85.756, 71.511, 31.596, 35.624, 74.761, 88.722, 96.389, 1.00, 6.362, 1.00, 20.387, 1.00, 1.363, 1.00, 14.214, 1.263, 25.936, 61.896]